/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-southeast-2",
  "aws_cognito_identity_pool_id": "ap-southeast-2:3f9cfd44-82d4-425e-affd-c291b527eedc",
  "aws_cognito_region": "ap-southeast-2",
  "aws_user_pools_id": "ap-southeast-2_IUReGReFf",
  "aws_user_pools_web_client_id": "4s4h4le1cu6r7rufrucmnj0r0e",
  "oauth": {}
};

export default awsmobile;
